Adding name and picture to girlcode yearbook
GirlCodeZA/glsde101-personal-website pull request #30
Opened 2021-05-04 09:06 UTC by Kamogelo98

yearbook

2021-05-10 20:55 UTC, anthonygraignic requested changes
Could you please restore the `my-profile-picture.png` file ?
Otherwise 👍

2021-05-12 05:42 UTC, anthonygraignic requested changes

2021-05-12 05:42 UTC, anthonygraignic commented on 2021/yearbook.html
> +        <img src="kamo.jpg" alt="Kamogelo" />
Please use the picture in the images folder `2021/images/kamo.jpg` so src=`images/kamo.jpg` and delete the file `2021/kamo.jpg`

2021-05-12 07:50 UTC, merged

2021-05-13 13:42 UTC, Kamogelo98 commented
Good Day

i tried fixing the stuff you mentioned so i can be part of the yearbook ,i
noticed i am however my picture is not appearing
please kindly assist

On Wed, 12 May 2021 at 09:50, Anthony Graignic ***@***.***>
wrote:

> Merged #30
> <https://github.com/GirlCodeZA/glsde101-personal-website/pull/30> into
> main.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GirlCodeZA/glsde101-personal-website/pull/30#event-4734541417>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATSTT6NSYBRZKDTZGIUJN2TTNIXOFANCNFSM44CKAMDA>
> .
>